### ISSUE TITLE
kibana.zip generic filename

### ISSUE THREAD

**Issue by alexoooo** [goodlabs-studio/kibana-plugin-drilldownmenu#1]
In the README file, there is a step to create a file called kibana.zip for the plugin.
Is that generic filename required by the plugin mechanism, or can it be something more specific to this particular plugin?

**Comment by pgege** [comment]
Its required, the folder with the plugin is stored inside Kibana.zip. From my experience, naming the folder anything other than Kibana.zip leads to errors.
