### ISSUE TITLE
incorrect behavior on Discover view

### ISSUE THREAD

**Issue by mmguero** [goodlabs-studio/kibana-plugin-drilldownmenu#3]
Great plugin, this has got a ton of potential uses. Thank you for releasing it.

I noticed that when I create a visualization the value's ⨁ drill-down option is presented correctly, which shows the URL in it as expected.

When in the Discovery view, however, the behavior does not seem correct (see screenshots)

- in the expanded document view, the details ⨁ icon is not present. There is a superfluous empty line after the value with a `>` arrow which can be "expanded", but which does not do anything:

![bug](https://user-images.githubusercontent.com/13872653/83528998-ff1f7700-a4a6-11ea-833b-47799f46a9e9.png)

- if you add the field to the "Selected Fields" so that it shows up in the header, you DO see the details ⨁ icon:

![header_not_expanded](https://user-images.githubusercontent.com/13872653/83529003-0050a400-a4a7-11ea-89f0-b06e3ef97e56.png)

- However, expanding it looks quite strange when expanded:

![header_expanded](https://user-images.githubusercontent.com/13872653/83529001-ffb80d80-a4a6-11ea-9122-fb2b5d17cce8.png)

I think the correct behavior would be:

- make sure the ⨁ icon to expand the details menu is visible for both the "Selected Fields" column values and the expanded view
- fix the way the drilldown menu looks when expanded from the "selected fields" column values

**Comment by mmguero** [comment]
I should mention, this is with Kibana 7.6.2

**Comment by mmguero** [comment]
I grabbed your changes and am getting this in my console.log when on the discover page:

```
TypeError: "rawValue.trim is not a function"
    DrillFormat https://malcolm.local.lan/kibana/bundles/commons.bundle.js:110
    recurse https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    wrap https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    convert https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    convert https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    formatHit https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    createBaseFor https://malcolm.local.lan/kibana/built_assets/dlls/vendors_1.bundle.dll.js:17
    baseForOwn https://malcolm.local.lan/kibana/built_assets/dlls/vendors_1.bundle.dll.js:17
    createForOwn https://malcolm.local.lan/kibana/built_assets/dlls/vendors_1.bundle.dll.js:17
    formatHit https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    SourceFormat https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    recurse https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    wrap https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    convert https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    convert https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    formatField https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    _displayField https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    createSummaryRow https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    createSummaryRow https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    link https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    watchMulti https://malcolm.local.lan/kibana/bundles/commons.bundle.js:1
    $digest https://malcolm.local.lan/kibana/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    evalAsync https://malcolm.local.lan/kibana/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    completeTask https://malcolm.local.lan/kibana/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
    o https://malcolm.local.lan/kibana/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:368
```

and this on a saved search table in a dashboard:

![Screenshot_2020-06-08 Overview - Kibana](https://user-images.githubusercontent.com/13872653/84060323-3f846680-a979-11ea-8e65-a883662bb37f.png)

Probably related to drill_down.ts:147?

**Comment by pgege** [comment]
Should be fixed now

**Comment by mmguero** [comment]
Thanks, I'll try it out!
